[package]
name = "hamos"
version = "0.1.0"
authors = ["hamadu <dercll1020@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"